name: MT Memes
favicon: null
layout_spectrum: 0.223
typography_spectrum: 0.28602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f7f7'
    - '#2e2e2e'
    - '#d2d2d2'
    - '#b0b0b0'
    - '#e96b0a'
  brandStrength: 0.9050104485359043
  lightness: 0.30241064936853945
  saturation: 0.4972205685917288
  rhythmicContrast: 0.7369836298748851
purpose: []
